### ISSUE TITLE
Unprocessbale Entity: only the first 1000 search results are available

### ISSUE THREAD

**Issue by kanghj** [mhilmiasyrofi/github-code-search#1]
Hello, 

I tried a query "org.joda.time.contrib.hibernate.PersistentInterval#nullSafeGet(java.sql.ResultSet,java.lang.String[],org.hibernate.engine.SessionImplementor,java.lang.Object)", but it returns me the following error: 

```
Response Code: 422
Unprocessbale Entity: only the first 1000 search results are available
See the documentation here: https://developer.github.com/v3/search/
--- Thread[main,5,main] END
```

Perhaps this error occurs for rarely used functions?

**Comment by mhilmiasyrofi** [comment]
Dear Mr. Hong Jin

Thank you for your error report. I really appreciate it!

After thoroughly examining the problem, I found that the error happened because of the [Github code search](https://github.com/search) limitation. The maximal searchable characters for github search are 128 characters. 
When my program parse your query, it become kind of this java String
`org.joda.time.contrib.hibernate.PersistentInterval nullSafeGet java.sql.ResultSet java.lang.String[] org.hibernate.engine.SessionImplementor java.lang.Object`. It uses 157 characters.

I got information by trying your query manually to github code search. You can reproduce it using this [link](https://github.com/search?q=org.joda.time.contrib.hibernate.PersistentInterval+nullSafeGet+java.sql.ResultSet%2Cjava.lang.String%5B%5D+org.hibernate.engine.SessionImplementor+java.lang.Object&type=Code).

**Comment by mhilmiasyrofi** [comment]
I've just added new commit changes that handle the query problem.
Again, thanks for the error report :)

**Comment by kanghj** [comment]
Great, thanks!

**Comment by mhilmiasyrofi** [comment]
thanks 🙏
